config/routes.rb
Rails.application.routes.draw do
  resources :custom_hosts, except: [:show]

  resources :test_results
  resources :load_tests
  resources :user_scenarios
  resources :aws_accounts
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  resources :test_schedules do
    get 'cancel'
  end

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root "welcome#index"
end

app/models/custom_host.rb
=begin
how i had to edit my local /etc/sudoers:
Defaults    env_keep += "rvm_bin_path GEM_HOME IRBRC MY_RUBY_HOME rvm_path rvm_prefix rvm_version GEM_PATH rvmsudo_secure_path RUBY_VERSION rvm_ruby_string rvm_delete_flag RUBYLIB _ORIGINAL_GEM_PATH RUBYOPT BUNDLE_GEMFILE rvm_user_install_flag rvm_loaded_flag rvm_stored_umask"

#last line:
eriks ALL = NOPASSWD: /Users/eriks/.rvm/gems/ruby-2.1.4/bin/ghost


.profile (for sh)- add line
export rvmsudo_secure_path=0

https://rvm.io/integration/sudo


=end


require 'resolv'

class CustomHost < ActiveRecord::Base

  #get absolute ghost path for any env
  GHOST_PATH = `which ghost`.chomp
  GHOST_LIST_REGEXP = /Listing\s(\d+)\shost\(s\):\s+([\w\W]+)/

  validates_presence_of :hostname, :description

  validates :ip_address, presence: true, format: { with: Resolv::IPv4::Regex }

  before_save :change_active
  after_save :ghost_list_valid?


  def activate!
    unless active
      add_ghost ? self.update(active: true) : false
    end
  end

  def deactivate!
    if active
      delete_ghost ? self.update(active: false) : false
    end
  end




  def ghost_list_valid?
    ghost_list = self.class.parse_ghost_list
    host_list = self.class.active_hosts.map { |host| [host.hostname, host.ip_address] }

    if ghost_list.sort != host_list.sort
      self.errors.add(:db_ghost_sync_error, "database and ghosts are out of sync")
      warn "Warning: active CustomHosts don't match active ghosts. Maybe try to re-sync the entire ghost list? If you were trying to save an existing custom host, it will be rolled back.", "\t" + {active_hosts: host_list, active_ghosts: ghost_list}.to_s
      raise ActiveRecord::RecordInvalid.new(self)
    end
    true
  end

  def self.parse_ghost_list
    list = list_ghosts
    if match_data = GHOST_LIST_REGEXP.match(list)
      lines = match_data[2].split("\n").map{ |str| str.gsub(/\s+/,"") }
      return ghost_array = lines.map { |line| line.split("->") }
    else
      []
    end
  end

  def self.bust_ghosts
    system("rvmsudo #{GHOST_PATH} bust")
  end


  def self.list_ghosts
    `#{GHOST_PATH} list`
  end

  def self.active_hosts
    self.all.where(active: true)
  end

  def change_active
    if self.active_changed?
      active ? add_ghost : delete_ghost
    end
  end

  def add_ghost
    system("rvmsudo #{GHOST_PATH} add #{hostname} #{ip_address}")
  end

  def delete_ghost
    if system("rvmsudo #{GHOST_PATH} delete #{hostname}")
      # binding.pry # to account for multiple identical hostnames
      if actives = self.class.active_hosts.reject { |host| host.id == self.id }.select { |host| host.hostname == self.hostname}
        actives.each(&:add_ghost)
      end
      return true
    end
  end


end

app/controllers/custom_hosts_controller.rb
class CustomHostsController < ApplicationController
  before_action :set_custom_host, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @custom_hosts = CustomHost.order(:hostname, active: :desc)
    # @hosts_json = @custom_hosts.as_json
    respond_with(@custom_hosts)
  end

  # def show
  #   respond_with(@custom_host)
  # end

  def new
    @custom_host = CustomHost.new
    respond_with(@custom_host)
  end

  def edit
  end

  def create
    @custom_host = CustomHost.new(strong_custom_host_params)
    if @custom_host.save
      redirect_to custom_hosts_path
    else
      respond_with(@custom_host)
    end
  end

  def update
    if request.xhr?
      p params
      # p params.class
      # p ajax_custom_host_params

      @custom_host.update(strong_custom_host_params) # strong params - see below
      render json: {host: @custom_host, ghostList: `ghost list`}
    else
      if @custom_host.update(strong_custom_host_params)
        redirect_to custom_hosts_path
      else
        respond_with(@custom_host)
      end
    end
  end

  def destroy
    @custom_host.destroy
    respond_with(@custom_host)
  end

  private
    def set_custom_host
      @custom_host = CustomHost.find(params[:id])
    end

    def custom_host_params
      params[:custom_host]
    end

    # !!! I added this. why no strong params in scaffolded method above?
    def strong_custom_host_params
      params.require(:custom_host).permit(:id, :active, :description, :hostname, :ip_address)
    end
end

app/helpers/custom_hosts_helper.rb
module CustomHostsHelper
end

app/views/custom_hosts/_form.html.erb
<div class="container">
  <%= form_for(@custom_host, html: {:class => "form-horizontal", :role => 'form'}) do |f| %>
      <%= render 'shared/form_error_message', object: @custom_host %>

      <div class="form-group">
        <%= f.label :hostname, class: 'control-label col-sm-2' %>
        <div class="col-sm-6">
          <%= f.text_field :hostname, class: 'form-control' %>
        </div>
      </div>



      <hr/>

      <div class="form-group">
        <%= f.label :description, class: 'control-label col-sm-2' %>
        <div class="col-sm-6">
          <%= f.text_field :description, class: 'form-control' %>
        </div>
      </div>

      <hr/>

      <div class="form-group">
        <%= f.label :ip_address, "I.P. Address", class: 'control-label col-sm-2' %>
        <div class="col-sm-6">
          <%= f.text_field :ip_address, class: 'form-control' %>
        </div>
      </div>



      <div class="actions">
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/custom_hosts/edit.html.erb
<div class="container">
  <!-- custom version of edit action bar without show path bc this object doesn't particularly need a show page-->
  <%#= render 'shared/edit_action_bar', title: 'Edit Custom host',
             object: @custom_host, objects_path: custom_hosts_path %>

  <div class="page-header">
    <div class="pull-right">
      <%#= link_to 'Show', object, :class => 'btn btn-info' %>
      <%= link_to 'All', custom_hosts_path, :class => 'btn btn-success' %>
    </div>
    <h2>Edit Custom Host</h2>

    <div class="clearfix"></div>
  </div>
  <%= render 'form' %>

</div>

app/views/custom_hosts/index.html.erb
<div class="container">
  <%= render 'shared/index_action_bar', title: 'Custom Hosts',
             new_object_path: new_custom_host_path %>

    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Hostname</th>
          <th>Description</th>
          <th>I.P. Address</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @custom_hosts.each do |host| %>
            <tr>
              <td><%= host.hostname %></td>
              <td><%= host.description %></td>
              <td><%= host.ip_address %></td>
              <td><input type="checkbox" class="switch" data-host-id="<%=host.id%>" data-hostname="<%= host.hostname %>" data-readonly="true" data-size="small" <%= 'checked=true' if host.active %>></td>
              <td>
                <div class="btn-group">
                  <!-- Show link - currently not needed? -->
                  <%#= link_to 'Show', host, :class => 'btn btn-info' %>

                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Actions <span class="caret"></span>
                  </button>

                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Edit', edit_custom_host_path(host) %></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Destroy', custom_host_path(host), :method => 'delete', data: {confirm: 'Are you sure?'} %></li>
                  </ul>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </table>

    <br>
  <% if Rails.env.development? %>
      <code>:> ghost list</code>
    <div> <pre id="ghost-list"><%= `ghost list` %></pre> </div>
  <% end %>

</div>

app/views/custom_hosts/new.html.erb
<div class="container">
  <%= render 'shared/new_action_bar', title: 'New Custom host',
             object: @custom_host, objects_path: custom_hosts_path %>

  <%= render 'form' %>
</div>

app/views/custom_hosts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_custom_host_path(@custom_host) %> |
<%= link_to 'Back', custom_hosts_path %>