config/routes.rb
Rails.application.routes.draw do
  resources :custom_hosts, except: [:show]

  resources :test_results
  resources :load_tests
  resources :user_scenarios
  resources :aws_accounts
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  resources :test_schedules do
    get 'cancel'
  end

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root "welcome#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @users = User.all.paginate(:page => params['page']).order('updated_at DESC')
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    if current_user.id == @user.id
      flash[:error] = 'Cannot delete the user you are current logged in with!'
      redirect_to users_url
    else
      @user.destroy
      respond_with(@user)
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {:class => "form-horizontal", :role => 'form'}) do |f| %>
  <%= render 'shared/form_error_message', object: @user %>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-4 control-label' %>
    <div class="col-sm-4">
      <%= f.email_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: 'col-sm-4 control-label' %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: 'col-sm-4 control-label' %>
    <div class="col-sm-4">
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4">&nbsp;</div>
    <div class="col-sm-4">
      <%= render 'shared/form_action_bar', f: f %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'shared/edit_action_bar', title: 'Edit User',
             object: @user, objects_path: users_path %>

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= render 'shared/index_action_bar', title: 'Users',
             new_object_path: new_user_path %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show', user, :class => 'btn btn-info' %>

            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Actions <span class="caret"></span>
            </button>

            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit', edit_user_path(user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Destroy', user_path(user), :method => 'delete', data: {confirm: 'Are you sure?'} %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="container">
  <%= render 'shared/new_action_bar', title: 'New User',
             objects_path: users_path %>

  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render 'shared/show_action_bar', title: 'Show User',
             objects_path: users_path,
             edit_object_path: edit_user_path %>

  <p><strong>Email:</strong> <%= @user.email %></p>
</div>