config/routes.rb
Rails.application.routes.draw do
  resources :custom_hosts, except: [:show]

  resources :test_results
  resources :load_tests
  resources :user_scenarios
  resources :aws_accounts
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  resources :test_schedules do
    get 'cancel'
  end

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root "welcome#index"
end

app/models/load_test.rb
class LoadTest < ActiveRecord::Base
  belongs_to :user_scenario
  validates :user_scenario, presence: true

  has_many :load_test_schedules, :dependent => :destroy
  accepts_nested_attributes_for :load_test_schedules, :reject_if => :all_blank, :allow_destroy => true

  validate do |load_test|
    load_test.errors.add(:base, 'Need at least one load test schedule') if load_test.load_test_schedules.length == 0
  end

  has_many :load_test_aws_ec2_instances, :dependent => :destroy
  accepts_nested_attributes_for :load_test_aws_ec2_instances, :reject_if => :all_blank, :allow_destroy => true

  has_many :aws_ec2_instances, :through => :load_test_aws_ec2_instances

  has_many :load_test_aws_rds_instances, :dependent => :destroy
  accepts_nested_attributes_for :load_test_aws_rds_instances, :reject_if => :all_blank, :allow_destroy => true

  has_many :aws_rds_instances, :through => :load_test_aws_rds_instances

  has_many :test_schedules, :dependent => :destroy

  validates :name, uniqueness: true, presence: true

  def schedule_graph_set
    schedule_set = Array.new
    schedule_set.push([0, 0])

    relative_time = 0

    self.load_test_schedules.each { |load_test_schedule|
      relative_time += load_test_schedule.duration
      schedule_set.push([relative_time, load_test_schedule.maximum_virtual_users])
    }
    return schedule_set
  end

  class << self
    def load_test_name_options
      names_sort = [['All', 'all']]

      test_names = self.select(:name).distinct
      test_names = test_names.map { |test_name| [test_name.name, test_name.name] }.sort
      test_names.each do |test_name|
        names_sort.push(test_name)
      end

      return names_sort
    end
  end
end

app/controllers/load_tests_controller.rb
class LoadTestsController < ApplicationController
  before_action :set_load_test, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @load_tests = LoadTest.all.paginate(:page => params['page']).order('updated_at DESC')
    respond_with(@load_tests)
  end

  def show
    respond_with(@load_test)
  end

  def new
    @load_test = LoadTest.new
    respond_with(@load_test)
  end

  def edit
  end

  def create
    @load_test = LoadTest.new(load_test_params)
    @load_test.save
    respond_with(@load_test)
  end

  def update
    @load_test.update(load_test_params)
    respond_with(@load_test)
  end

  def destroy
    @load_test.destroy
    respond_with(@load_test)
  end

  private
  def set_load_test
    @load_test = LoadTest.find(params[:id])
  end

  def load_test_params
    params.require(:load_test).permit(:user_scenario_id, :name,
                                      load_test_schedules_attributes: [:id, :maximum_virtual_users, :duration, :_destroy],
                                      load_test_aws_ec2_instances_attributes: [:id, :aws_ec2_instance_id, :metric, :_destroy],
                                      load_test_aws_rds_instances_attributes: [:id, :aws_rds_instance_id, :metric, :_destroy])
  end
end

app/helpers/load_tests_helper.rb
module LoadTestsHelper
end

app/views/load_tests/_form.html.erb
<%= form_for(@load_test, html: {:class => "form-horizontal", :role => 'form'}) do |f| %>
    <%= render 'shared/form_error_message', object: @load_test %>

    <div class="form-group">
      <%= f.label :name, class: 'control-label col-sm-2' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :user_scenario_id, class: 'control-label col-sm-2' %>
      <div class="col-sm-6">
        <%= f.collection_select(:user_scenario_id, UserScenario.all, :id, :name, {:prompt => 'Please Select User Scenario'}, {:class => 'form-control'}) %>
      </div>
    </div>

    <hr/>

    <div class="form-group">
      <label class="control-label col-sm-2">Load Test Schedules</label>

      <div class="col-sm-5">
        <div class="load_test_schedules">
          <%= f.fields_for :load_test_schedules do |load_test_schedule| %>
              <%= render 'load_test_schedule_fields', f: load_test_schedule %>
          <% end %>
        </div>
        <%= link_to_add_association 'Add', f, :load_test_schedules,
                                    'data-association-insertion-method' => :append,
                                    'data-association-insertion-node' => '.load_test_schedules',
                                    :class => 'btn btn-default' %>
      </div>
      <div class="col-sm-5">
        <div id="load_test_schedule_chart" style="height: 200px;"></div>
      </div>
    </div>

    <hr/>

    <div class="form-group">
      <label class="control-label col-sm-2">AWS EC2 Server Metrics</label>

      <div class="col-sm-10">
        <div class="load_test_aws_ec2_instances">
          <%= f.fields_for :load_test_aws_ec2_instances do |load_test_aws_ec2_instance| %>
              <%= render 'load_test_aws_ec2_instance_fields', f: load_test_aws_ec2_instance %>
          <% end %>
        </div>
        <%= link_to_add_association 'Add', f, :load_test_aws_ec2_instances,
                                    'data-association-insertion-method' => :append,
                                    'data-association-insertion-node' => '.load_test_aws_ec2_instances',
                                    :class => 'btn btn-default' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2">AWS RDS Server Metrics</label>

      <div class="col-sm-10">
        <div class="load_test_aws_rds_instances">
          <%= f.fields_for :load_test_aws_rds_instances do |load_test_aws_rds_instance| %>
              <%= render 'load_test_aws_rds_instance_fields', f: load_test_aws_rds_instance %>
          <% end %>
        </div>
        <%= link_to_add_association 'Add', f, :load_test_aws_rds_instances,
                                    'data-association-insertion-method' => :append,
                                    'data-association-insertion-node' => '.load_test_aws_rds_instances',
                                    :class => 'btn btn-default' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/load_tests/_load_test_aws_ec2_instance_fields.html.erb
<div class="nested-fields input-group">
  <%= f.collection_select(:aws_ec2_instance_id, AwsEc2Instance.all, :id, :full_name, {:prompt => 'Please Select EC2 Instance'}, {:class => 'form-control'}) %>
  <span class="input-group-btn" style="width:0px;"></span>
  <%= f.select(:metric, AMAZON_METRICS['EC2'].map { |value| [value, value] }, {:prompt => 'Please Select Metric'}, {:class => 'form-control', :style => 'margin-left:-1px'}) %>
  <span class="input-group-btn">
        <%= link_to_remove_association "Remove", f, :class => 'btn btn-danger', :style => 'margin-left:-2px' %>
  </span>
</div>

app/views/load_tests/_load_test_aws_rds_instance_fields.html.erb
<div class="nested-fields input-group">
  <%= f.collection_select(:aws_rds_instance_id, AwsRdsInstance.all, :id, :full_name, {:prompt => 'Please Select RDS Instance'}, {:class => 'form-control'}) %>
  <span class="input-group-btn" style="width:0px;"></span>
  <%= f.select(:metric, AMAZON_METRICS['RDS'].map { |value| [value, value] }, {:prompt => 'Please Select Metric'}, {:class => 'form-control', :style => 'margin-left:-1px'}) %>
  <span class="input-group-btn">
        <%= link_to_remove_association "Remove", f, :class => 'btn btn-danger', :style => 'margin-left:-2px' %>
  </span>
</div>

app/views/load_tests/_load_test_schedule_fields.html.erb
<div class="nested-fields input-group">
  <%= f.number_field :duration, class: 'form-control', :placeholder => 'Duration (Minutes)', min: 0 %>
  <span class="input-group-btn" style="width:0px;"></span>
  <%= f.number_field :maximum_virtual_users, class: 'form-control', :placeholder => 'Max Virtual Users', :style => 'margin-left:-1px', min: 0 %>
  <span class="input-group-btn">
        <%= link_to_remove_association "Remove", f, :class => 'btn btn-danger', :style => 'margin-left:-2px' %>
  </span>
</div>

app/views/load_tests/edit.html.erb
<div class="container">
  <%= render 'shared/edit_action_bar', title: 'Edit Load Test',
             object: @load_test, objects_path: load_tests_path %>

  <%= render 'form' %>
</div>

app/views/load_tests/index.html.erb
<div class="container">
  <%= render 'shared/index_action_bar', title: 'Load Tests',
             new_object_path: new_load_test_path %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>User Scenario</th>
      <th>Dimensions</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @load_tests.each do |load_test| %>
      <tr>
        <td>
          <%= truncate load_test.name, :length => 25, :separator => /\w/,
                       :omission => '...' %>
        </td>
        <td>
          <%= truncate load_test.user_scenario.name, :length => 25, :separator => /\w/,
                       :omission => '...' %>
        </td>
        <td>
          <%= load_test.load_test_schedules.sum(:duration) %> minutes,
          <%= load_test.load_test_schedules.maximum(:maximum_virtual_users) %> max users
        </td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show', load_test, :class => 'btn btn-info' %>

            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Actions <span class="caret"></span>
            </button>

            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit', edit_load_test_path(load_test) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Destroy', load_test_path(load_test), :method => 'delete', data: {confirm: 'Are you sure?'} %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5">
        <%= will_paginate @load_tests, renderer: BootstrapPagination::Rails %>
      </td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/load_tests/new.html.erb
<div class="container">
  <%= render 'shared/new_action_bar', title: 'New Load Test',
             objects_path: load_tests_path %>

  <%= render 'form' %>
</div>

app/views/load_tests/show.html.erb
<div class="container">
  <%= render 'shared/show_action_bar', title: 'Show Load Test',
             objects_path: load_tests_path,
             edit_object_path: edit_load_test_path %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">User Scenario: <%= link_to @load_test.user_scenario.name, @load_test.user_scenario %></h3>
    </div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>#</th>
        <th>Request Type</th>
        <th>Request URL</th>
      </tr>
      </thead>
      <tbody>
      <% if @load_test.user_scenario.user_scenario_steps.count > 0 %>
        <% @load_test.user_scenario.user_scenario_steps.each_with_index do |user_scenario_step, index| %>
          <tr>
            <td><%= index + 1 %></td>
              <td><%= user_scenario_step.request_type %></td>
              <td>
                <%= truncate user_scenario_step.request_url, :length => 25, :separator => /\w/,
                             :omission => '...' %>
              </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Load Test Schedules</h3>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>Max Virtual Users</th>
            <th>Duration (Minutes)</th>
          </tr>
          </thead>
          <tbody>
          <% if @load_test.load_test_schedules.count > 0 %>
            <% @load_test.load_test_schedules.each_with_index do |load_test_schedule, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= load_test_schedule.maximum_virtual_users %></td>
                <td><%= load_test_schedule.duration %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="2">None</td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-sm-6">
        <%= line_chart @load_test.schedule_graph_set, {
          :discrete => true,
          :height => '200px',
          library:
            {
              curveType: 'none',
              hAxis: {
                      title: 'Duration (Minutes)'
              },
              vAxis:
                {
                  title: 'Maximum Virtual Users'
                }
            }
        } %>
      </div>
    </div>

  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">AWS EC2 Server Metrics</h3>
    </div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Instance ID</th>
        <th>Metric</th>
      </tr>
      </thead>
      <tbody>
      <% if @load_test.load_test_aws_ec2_instances.count > 0 %>
        <% @load_test.load_test_aws_ec2_instances.each do |load_test_aws_ec2_instance| %>
          <tr>
            <td>
              <%= link_to load_test_aws_ec2_instance.aws_ec2_instance.full_name, load_test_aws_ec2_instance.aws_ec2_instance.aws_account %>
            </td>
            <td><%= load_test_aws_ec2_instance.aws_ec2_instance.instance_id %></td>
            <td><%= load_test_aws_ec2_instance.metric %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="2">None</td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">AWS RDS Server Metrics</h3>
    </div>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>DB Instance Identifier</th>
        <th>Metric</th>
      </tr>
      </thead>
      <tbody>
      <% if @load_test.load_test_aws_rds_instances.count > 0 %>
        <% @load_test.load_test_aws_rds_instances.each do |load_test_aws_rds_instance| %>
          <tr>
            <td>
              <%= link_to load_test_aws_rds_instance.aws_rds_instance.full_name, load_test_aws_rds_instance.aws_rds_instance.aws_account %>
            </td>
            <td><%= load_test_aws_rds_instance.aws_rds_instance.db_instance_identifier %></td>
            <td><%= load_test_aws_rds_instance.metric %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="2">None</td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>